package unsafely

import (
	"github.com/outriggerlabs/unsafely/typeutil"
)

// UnmarshalJSON deserializes a JSON string to the output value, including
// unexported fields.
//
// The output must be a pointer and the JSON string must have been generated by
// MarshalJSON.
//
// See the package notes for restrictions, limitations and options.
func UnmarshalJSON(b []byte, outPtr any, options ...UnmarshalJSONOption) error {
	return NewJSONDecoder(options...).Decode(b, outPtr)
}

// Configuration options for UnmarshalJSON.
type unmarshalJSONConfig struct {
	typeResolver typeutil.Resolver
}

// UnmarshalJSONOption is an option for modifying the behavior of UnmarshalJSON.
type UnmarshalJSONOption func(*unmarshalJSONConfig)

// WithTypeResolver sets the typeutil.Resolver used to create new instances of
// types by name.
func WithTypeResolver(resolver typeutil.Resolver) UnmarshalJSONOption {
	return func(config *unmarshalJSONConfig) {
		config.typeResolver = resolver
	}
}
